config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users
  resources :menus do
    resources :menu_reviews
    member do
      get :confirm
      post :order
    end
  end
  resources :stores
  resources :user_purchase_histories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_menu.rb
class AvailableMenu < ApplicationRecord
  belongs_to :store
  belongs_to :menu
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_reviews

  has_many :user_purchase_histories
  belongs_to :store

  mount_uploader :image, ImageUploader

  def average_star
    stars = self.menu_reviews.pluck(:star)
    if stars.present?
      stars.sum(0.0) / stars.size
    else
      0
    end
  end
end

app/models/menu_review.rb
class MenuReview < ApplicationRecord
  belongs_to :user
  belongs_to :menu
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :user_purchase_histories
  has_many :menus

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :menu_reviews
  has_many :user_purchase_histories

  mount_uploader :image, ImageUploader
end

app/models/user_purchase_history.rb
class UserPurchaseHistory < ApplicationRecord
  belongs_to :user
  belongs_to :store
  belongs_to :menu

  class Status
    PREPARING = 1
    WAITING = 2
    SUCCESS = 3
    CANCELLED = 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    if params[:op] == 'highly_rated'
      @menus = Menu.all.sort_by { |menu| -menu.average_star }
    elsif params[:op] == 'latest'
      @menus = Menu.all.order(created_at: "DESC")
    else
      @menus = Menu.all
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new()
  end

  def create
    menu = Menu.new(menu_params)
    menu.save!
    # TODO: indexに飛ばす
    redirect_to '/'
  end

  def confirm
    @menu = Menu.find(params[:id])
  end

  def order
    @menu = Menu.find(params[:id])

    # 注文処理
    user_purchase_history = UserPurchaseHistory.new
    user_purchase_history.user = User.first
    user_purchase_history.store = Store.first
    user_purchase_history.menu = @menu

    user_purchase_history.status = UserPurchaseHistory::Status::PREPARING

    if user_purchase_history.save
      user_purchase_history_id = 10
      redirect_to user_purchase_histories_path, notice: "注文を完了しました。お店に確認中です。"
    else
      # TODO
    end
  end

  private

  def menu_params
    params.require(:menu).permit(:store_id, :name, :description, :time, :price, :ingredients_text, :recipe_text, :image)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/user_purchase_histories_controller.rb
class UserPurchaseHistoriesController < ApplicationController
  def index
    @user_purchase_histories = UserPurchaseHistory.where(status: UserPurchaseHistory::Status::PREPARING)
                              .or(UserPurchaseHistory.where(status: UserPurchaseHistory::Status::WAITING))
    @old_user_purchase_histories = UserPurchaseHistory.where(status: UserPurchaseHistory::Status::SUCCESS)
                                   .or(UserPurchaseHistory.where(status: UserPurchaseHistory::Status::CANCELLED))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def star_numbers(average)
    quo, mod = (average / 0.5).floor.divmod(2)
    return quo, mod
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_purchase_history_helper.rb
module UserPurchaseHistoryHelper
end

app/views/layouts/application.html.haml
!!!

= stylesheet_link_tag 'application', media: 'all'
= javascript_include_tag 'application'
= javascript_pack_tag 'application'

%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NeighborFood
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body
    %nav.navbar.navbar-light.bg-light
      %a.navbar-brand{href: '/'}
        = image_tag "logo-black.png", width: "40px"
        NeighborFood
      %button.navbar-toggler.collapsed{"aria-controls": "navbarSupportedContent", "aria-expanded": "false", "aria-label": "Toggle navigation", "data-target": "#navbarSupportedContent", "data-toggle": "collapse", type: "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            = link_to "お近くの評価が高いセット", menus_path(op: "highly_rated"), class: 'nav-link'
          %li.nav-item
            = link_to "お近くの新着セット", menus_path(op: "latest"), class: 'nav-link'
          %li.nav-item
            = link_to "注文履歴", user_purchase_histories_path, class: 'nav-link'
          %li.nav-item
            -# TODO
            = link_to "マイページ", user_path(1), class: 'nav-link'
        %p.navbar-text.navbar-right
          ようこそ
          %a.navbar-link{:href => "#"} ゲスト
          さん。

    = yield

app/views/menus/confirm.html.haml
.jumbotron
  %h1
    ご注文

.p-3.container
  = image_tag @menu.image.url, style: 'width: 80%;height: auto'
  %h3
    セット情報
  %table.table.table-hover.my-4
    %tbody
      %tr
        %th
          セット名
        %td
          = @menu.name
      %tr
        %th
          食材一覧
        %td
          = @menu.ingredients_text
  %h3
    店舗情報
  %table.table.table-hover.my-4
    %tbody
      %tr
        %th
          店舗名
        %td
          = @menu.store.name
      %tr
        %th
          店舗概要
        %td
          = @menu.store.description
  %h3
    ご請求額
    %table.table.table-hover.my-4
      %tbody
        %tr
          %td
            = "￥ #{@menu.price}"
  %h3
    地図（デモ）
  %p.ml-2
    = image_tag 'map_demo.png', style: 'width: 80%;height: auto'

  = link_to '注文する', order_menu_path(@menu), method: :post, class: 'btn btn-primary ml-1'

app/views/menus/index.html.haml
.p-3.container
  %h3.mt-1
    - if params[:op] == 'highly_rated'
      お近くの評価が高いセット一覧
    - elsif params[:op] == 'latest'
      お近くの新着セット一覧
    - else
      メニュー一覧
  - @menus.each do |menu|
    .row.py-1
      .col-12
        .card
          .d-flex.shadow.rounded
            = image_tag menu.image.url, style: 'width: 45%;height: auto'
            .card-body
              %h5.card-title
                = menu.name
              %h6.card-subtitle.mb-2.text-muted
                = menu.description
              %p.card-text
                -# レビュー評価の平均値分だけ星を出す
                -# TODO: 整理する, DRYにする
                - quo, mod = star_numbers(menu.average_star)
                - quo.times do |i|
                  = icon 'fas', 'star'
                - mod.times do |i|
                  = icon 'fas', 'star-half-alt'
                - (5 - (quo + mod)).times do |i|
                  = icon 'far', 'star'
                %span
                  .d-inline
                    = icon 'fas', 'map-marker-alt'
                  .d-inline.text-muted
                    = "#{rand(1..10) * 100} M"
              = link_to "詳細を見る", menu_path(menu), class: 'btn btn-primary'

app/views/menus/new.html.haml
= form_with model: @menu, local: true do |f|
  .form-group
    = f.label "名前"
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label "ストアID"
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label "概要"
    = f.text_field :description, class: 'form-control'
  .form-group
    = f.label "値段"
    = f.text_field :price, class: 'form-control'
  .form-group
    = f.label "所要時間"
    = f.text_field :time, class: 'form-control'
  .form-group
    = f.label "材料"
    = f.text_area :ingredients_text, class: 'form-control'
  .form-group
    = f.label "レシピ"
    = f.text_area :recipe_text, class: 'form-control'
  .form-group
    = f.label "画像"
    = f.file_field :image, accept: "image/png,image/gif,image/jpeg", class: 'form-control'
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/menus/show.html.haml
.jumbotron
  %h1
    = @menu.name

.p-3.container
  = image_tag @menu.image.url, style: 'width: 80%;height: auto'
  %h3
    セット情報
  %table.table.table-hover.my-4
    %tbody
      %tr
        %th
          セット名
        %td
          = @menu.name
      %tr
        %th
          概要
        %td
          = @menu.description
      %tr
        %th
          所要時間
        %td
          = @menu.time
      %tr
        %th
          食材一覧
        %td
          = simple_format(@menu.ingredients_text)
      %tr
        %th
          レシピ
        %td
          = simple_format(@menu.recipe_text)
  %h3
    店舗情報
  %table.table.table-hover.my-4
    %tbody
      %tr
        %th
          店舗名
        %td
          = @menu.store.name
      %tr
        %th
          評価
        %td
          = icon 'fas', 'star'
          = icon 'fas', 'star'
          = icon 'fas', 'star'
          = icon 'fas', 'star'
          = icon 'fas', 'star-half-alt'
      %tr
        %th
          店舗概要
        %td
          = @menu.store.description
  %h3
    ご請求額
    %table.table.table-hover.my-4
      %tbody
        %tr
          %td
            = "￥ #{@menu.price}"
  %h3
    地図（デモ）
  %p.ml-2
    = image_tag 'map_demo.png', style: 'width: 80%;height: auto'

  = link_to '注文画面に進む', confirm_menu_path(@menu), class: 'btn btn-primary ml-1'

app/views/top/index.html.haml
= image_tag 'cooking.png', class: 'img-fluid'

.jumbotron
  %h1
    NeighborFood
  %p.ml-2.text-muted
    レシピを選んで注文するだけ！
    %br
    お近くの提携店舗でレシピに必要な食材が受け取れます。

.p-3.container
  - if flash.notice.present?
    .alert.alert-success= flash.notice
  %h3.mt-1
    お近くの新着セット
  %p.text-right
    = link_to "もっと見る >", menus_path(op: "latest")
  // TODO: キョリとcreated_atでソート
  - Menu.all.limit(4).order(:id).each do |menu|
    .row.py-1
      .col-12
        .card
          .d-flex.shadow.rounded
            = image_tag menu.image.url, style: 'width: 45%;height: auto'
            .card-body
              %h5.card-title
                = menu.name
              %h6.card-subtitle.mb-2.text-muted
                = menu.description
              %p.card-text
                -# レビュー評価の平均値分だけ星を出す
                -# TODO: 整理する, DRYにする
                - quo, mod = star_numbers(menu.average_star)
                - quo.times do |i|
                  = icon 'fas', 'star'
                - mod.times do |i|
                  = icon 'fas', 'star-half-alt'
                - (5 - (quo + mod)).times do |i|
                  = icon 'far', 'star'
                %span
                  .d-inline
                    = icon 'fas', 'map-marker-alt'
                  .d-inline.text-muted
                    = "#{rand(1..10) * 100} M"
              = link_to "詳細を見る", menu_path(menu), class: 'btn btn-primary'
  %h3.mt-5
    お近くの評価が高いセット
  %p.text-right
    = link_to "もっと見る >", menus_path(op: "highly_rated")
  // TODO: キョリと評価でソート
  - Menu.all.limit(4).order(:id).each do |menu|
    .row.py-1
      .col-12
        .card
          .d-flex.shadow
            = image_tag menu.image.url, style: 'width: 45%;height: auto'
            .card-body
              %h5.card-title
                = menu.name
              %h6.card-subtitle.mb-2.text-muted
                = menu.description
              %p.card-text.pt-1
                -# レビュー評価の平均値分だけ星を出す
                - quo, mod = star_numbers(menu.average_star)
                - quo.times do |i|
                  = icon 'fas', 'star'
                - mod.times do |i|
                  = icon 'fas', 'star-half-alt'
                - (5 - (quo + mod)).times do |i|
                  = icon 'far', 'star'
                %br
                %span
                  .d-inline
                    = icon 'fas', 'map-marker-alt'
                  .d-inline.text-muted
                    = "#{rand(1..10) * 100} M"
              = link_to "詳細を見る", menu_path(menu), class: 'btn btn-primary'

app/views/user_purchase_histories/index.html.haml
.jumbotron
  %h1
    注文履歴

.p-3.container
  - if flash.notice.present?
    .alert.alert-success= flash.notice
  %h3
    完了していない注文
  - @user_purchase_histories.each do |history|
    .row
      .col-12
        .card.bg-light
          .card-body
            %h5.card-title
              = link_to history.menu.name, menu_path(history.menu), class: 'text-dark'
            %h6.card-subtitle.mb-2.text-muted.mt-3
              - if history.status == UserPurchaseHistory::Status::PREPARING
                %span.badge.badge-primary
                  お店に確認中
              - elsif history.status == UserPurchaseHistory::Status::WAITING
                %span.badge.badge-success
                  受け渡し待機中
              - elsif history.status == UserPurchaseHistory::Status::SUCCESS
                %span.badge.badge-secondary
                  受け渡し完了済み
              - elsif history.status == UserPurchaseHistory::Status::CANCELLED
                %span.badge.badge-danger
                  キャンセル済み
              -# TODO: 元気があったらlocaleに変える
              = "￥#{history.menu.price}"
              .span
                = history.created_at.strftime('%Y/%m/%d %H:%M:%S')
            %p.card-text
              = link_to history.store.name, store_path(history.store), class: 'text-muted'

  %h3.mt-4
    完了済みの注文
  - @old_user_purchase_histories.each do |history|
    .row
      .col-12
        .card.bg-light
          .card-body
            %h5.card-title
              = link_to history.menu.name, menu_path(history.menu), class: 'text-dark'
            %h6.card-subtitle.mb-2.text-muted.mt-3
              - if history.status == UserPurchaseHistory::Status::PREPARING
                %span.badge.badge-primary
                  お店に確認中
              - elsif history.status == UserPurchaseHistory::Status::WAITING
                %span.badge.badge-success
                  受け渡し待機中
              - elsif history.status == UserPurchaseHistory::Status::SUCCESS
                %span.badge.badge-secondary
                  受け渡し完了済み
              - elsif history.status == UserPurchaseHistory::Status::CANCELLED
                %span.badge.badge-danger
                  キャンセル済み
              = "￥#{history.menu.price}"
              .span
                -# TODO: 元気があったらlocaleに変える
                = history.created_at.strftime('%Y/%m/%d %H:%M:%S')
            %p.card-text
              = link_to history.store.name, store_path(history.store), class: 'text-muted'

app/views/user_purchase_histories/show.html.haml
.jumbotron
  %h1
    注文履歴

.p-3.container
  %h3